Fix IllegalStateException when running tests in IntelliJ
java.lang.IllegalStateException: Is your TestPipeline declaration
missing a @Rule annotation? Usage: @Rule public final transient
TestPipeline pipeline = TestPipeline.Create();